package com.example.wallet.helpers

object Strings {
    const val CONNECTION_ERROR = "Connection error"
    const val SUCCESSFUL_REGISTRATION = "User registered"
    const val FAILED_REGISTRATION = "Registration error"
    const val FAILED_LOGIN = "Login error"
    const val USERNAME_TEXTFIELD_TAG = "usernameTextField"
    const val PASSWORD_TEXTFIELD_TAG = "passwordTextField"
    const val SET_BUDGET_TEXTFIELD_TAG = "setBudget"
    const val EXCEED_BUDGET_TEXTFIELD_TAG = "exceedBudget"
    const val BOTTOM_NAV_BAR = "bottomNavBar"
    const val EMPTY_ADD_FILED = "emptyAddField"
    const val ADD_CATEGORY_NAME = "addCategoryName"
    const val ADD_WALLET_NAME = "addWalletName"
    const val ADD_TRANSACTION_NAME = "addTransactionName"
    const val ADD_TRANSACTION_AMOUNT = "ADD_TRANSACTION_AMOUNT"
    const val ADD_TRANSACTION_TYPE = "ADD_TRANSACTION_TYPE"
    const val ADD_TRANSACTION_CATEGORY = "ADD_TRANSACTION_CATEGORY"
    const val ADD_TRANSACTION_WALLET = "ADD_TRANSACTION_WALLET"
    const val ADD_TRANSACTION_DATE = "ADD_TRANSACTION_DATE"
    const val ADD_TRANSACTION_COMMENTS = "ADD_TRANSACTION_COMMENTS"
    const val ADD_TRANSACTION_LOCATION = "ADD_TRANSACTION_LOCATION"
    const val ADD_TRANSACTION_SCREEN = "ADD_TRANSACTION_SCREEN"
    const val REPORT_SCREEN = "REPORT_SCREEN"
}